server:
  port: 8085
  servlet:
    context-path: /airfile
  tomcat:
    uri-encoding: utf-8

springdoc:
  api-docs:
    path: /api-docs
    show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tryItOutEnabled: false
    filter: false
    syntaxHighlight:
      activated: true

spring:
  config:
    import: classpath:redisson.yml,
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      mode: always

  datasource:
    url: jdbc:h2:file:./data/batch-db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: "true"
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

airfile:
  schedule:
    fileType:
      interval: 30000

  storage:
    minio:
      enable: false
      url: http://localhost:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucket: resumes
      
    localFile:
      enable: true
      path: "/Users/nandin.pao/Documents/agitg/source/fileflow/airfile/upload"
